### ISSUE TITLE
Integrate Wizard of Wikipedia into agent list

### ISSUE THREAD

**Issue by mrhegemon** [XRFoundation/DigitalBeing#130]
https://github.com/hyunwoongko/openchat from OpenChat

**Comment by ogeagla** [comment]
@taimoorkhokhar , @mrhegemon  and I talked about this yesterday a bit and I have started to work on this, going to create a new issue and link here if no objections.

**Comment by taimoorkhokhar** [comment]
@ogeagla @mrhegemon This is already wired up. That's why I closed it
