### ISSUE TITLE
[Question] Documentation

### ISSUE THREAD

**Issue by chris-aeviator** [XRFoundation/DigitalBeing#304]
Hi, I can roughly get an idea what DigitalBeing is about. Is there a demo or a video or a more extensive documentation on what to build with this toolkit and how?

**Comment by alextitonis** [comment]
I will record a small video to show more, basically you can connect any type of agents, using the Python Server Side (like the examples) with the Created Clients (discord, xr-engine, telegram, twitter etc)

**Comment by chris-aeviator** [comment]
thanks for your reply - when will the project have a detailed written documentation? As a developer or systems architect I only pick a project if it is mature enough to justify my time spending on it.

**Comment by alextitonis** [comment]
I will work on that this week thanks for your patience

**Comment by alextitonis** [comment]
Here you can find a more detailed document about Digital Being, if you have any comments feel free to put https://docs.google.com/document/d/1h-nq736F67zxk2MfpDKBSidquRTmjpWmb_Qv_mLeAfI/edit?usp=sharing 
I'm going to apply it soon in the readme too

**Comment by jack-solutions** [comment]
same question as @chris-aeviator , Is there a demo or a video of it?
